-- MySQL Script generated by MySQL Workbench
-- Tue Mar 24 19:09:47 2020
-- Model: Efake    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `Efake`.`CATEGORIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Efake`.`CATEGORIA` ;

CREATE TABLE IF NOT EXISTS `Efake`.`CATEGORIA` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
CHARACTER SET 'utf8';


-- -----------------------------------------------------
-- Table `Efake`.`Keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Efake`.`Keywords` ;

CREATE TABLE IF NOT EXISTS `Efake`.`KEYWORDS` (
  `Palabra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Palabra`))
CHARACTER SET 'utf8';


-- -----------------------------------------------------
-- Table `Efake`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Efake`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `Efake`.`USUARIO` (
  `Correo` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(100) NOT NULL,
  `Edad` INT(11) NOT NULL,
  `Telefono` VARCHAR(13) NULL DEFAULT NULL,
  `Imagen` VARCHAR(100) NULL DEFAULT 'https://lifeatbrio.com/wp-content/uploads/2016/11/user-placeholder.jpg',
  `esAdmin` TINYINT(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`Correo`),
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC))
CHARACTER SET 'utf8';


-- -----------------------------------------------------
-- Table `Efake`.`SUBCATEGORIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Efake`.`SUBCATEGORIA` ;

CREATE TABLE IF NOT EXISTS `Efake`.`SUBCATEGORIA` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` LONGTEXT NULL DEFAULT NULL,
  `Categoria` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `categoria_idx` (`Categoria` ASC) VISIBLE,
  CONSTRAINT `categoria`
    FOREIGN KEY (`Categoria`)
    REFERENCES `Efake`.`CATEGORIA` (`ID`))

AUTO_INCREMENT = 2
CHARACTER SET 'utf8';


-- -----------------------------------------------------
-- Table `Efake`.`PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Efake`.`PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `Efake`.`PRODUCTO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` LONGTEXT NULL DEFAULT NULL,
  `Precio` DOUBLE NOT NULL,
  `Imagen` TEXT NULL DEFAULT NULL,
  `Fecha` DATETIME NOT NULL,
  `Categoria` INT(11) NOT NULL,
  `Subcategoria` INT(11) NULL DEFAULT NULL,
  `Owner` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `categoria_producto_idx` (`Categoria` ASC),
  INDEX `owner_idx` (`Owner` ASC),
  INDEX `subcategoria_idx` (`Subcategoria` ASC),
  CONSTRAINT `categoria_producto`
    FOREIGN KEY (`Categoria`)
    REFERENCES `Efake`.`CATEGORIA` (`ID`),
  CONSTRAINT `owner`
    FOREIGN KEY (`Owner`)
    REFERENCES `Efake`.`USUARIO` (`Correo`),
  CONSTRAINT `subcategoria`
    FOREIGN KEY (`Subcategoria`)
    REFERENCES `Efake`.`SUBCATEGORIA` (`ID`))
CHARACTER SET 'utf8';


-- -----------------------------------------------------
-- Table `Efake`.`VALORACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Efake`.`VALORACION` ;

CREATE TABLE IF NOT EXISTS `Efake`.`VALORACION` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Puntuacion` INT(11) NOT NULL,
  `Comentario` LONGTEXT NULL DEFAULT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `Cliente` VARCHAR(100) NULL DEFAULT NULL,
  `ProductoValorado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `cliente_idx` (`Cliente` ASC),
  INDEX `producto_idx` (`ProductoValorado` ASC) ,
  CONSTRAINT `cliente`
    FOREIGN KEY (`Cliente`)
    REFERENCES `Efake`.`USUARIO` (`Correo`),
  CONSTRAINT `producto`
    FOREIGN KEY (`ProductoValorado`)
    REFERENCES `Efake`.`PRODUCTO` (`ID`))
CHARACTER SET 'utf8';


-- -----------------------------------------------------
-- Table `Efake`.`PRODUCTO_KEYWORDS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Efake`.`PRODUCTO_KEYWORDS` ;

CREATE TABLE IF NOT EXISTS `Efake`.`PRODUCTO_KEYWORDS` (
  `Producto` INT(11) NOT NULL,
  `Palabra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Producto`, `Palabra`),
  INDEX `fk_PRODUCTO_has_Keywords_Keywords1_idx` (`Palabra` ASC) ,
  INDEX `fk_PRODUCTO_has_Keywords_PRODUCTO1_idx` (`Producto` ASC) ,
  CONSTRAINT `fk_PRODUCTO_has_Keywords_PRODUCTO1`
    FOREIGN KEY (`Producto`)
    REFERENCES `Efake`.`PRODUCTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_has_Keywords_Keywords1`
    FOREIGN KEY (`Palabra`)
    REFERENCES `Efake`.`KEYWORDS` (`Palabra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

CHARACTER SET 'utf8';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
